<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jjME_E3' shared service.

return $this->privates['.service_locator.jjME_E3'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repository' => function (): \App\Repository\ProfesseurRepository {
    return ($this->privates['App\Repository\ProfesseurRepository'] ?? $this->load('getProfesseurRepositoryService.php'));
}));
