<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7GzW1ZE' shared service.

return $this->privates['.service_locator.7GzW1ZE'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repository' => function (): \App\Repository\EtudiantRepository {
    return ($this->privates['App\Repository\EtudiantRepository'] ?? $this->load('getEtudiantRepositoryService.php'));
}));
