<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.q3T6Ejk.App\Entity\Competences' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.q3T6Ejk": it references class "App\\Entity\\Competences" but no such service exists.');
