<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.t6x6YdK.App\Entity\Maison' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.t6x6YdK": it references class "App\\Entity\\Maison" but no such service exists.');
