<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DSuC8HQ' shared service.

return $this->privates['.service_locator.DSuC8HQ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repository' => function (): \App\Repository\CompetencesRepository {
    return ($this->privates['App\Repository\CompetencesRepository'] ?? $this->load('getCompetencesRepositoryService.php'));
}));
