<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.q3T6Ejk' shared service.

return $this->privates['.service_locator.q3T6Ejk'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('uneCompetence' => function (): \App\Entity\Competences {
    return ($this->privates['.errored..service_locator.q3T6Ejk.App\Entity\Competences'] ?? $this->load('getCompetencesService.php'));
}));
