<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.J.inxYp' shared service.

return $this->privates['.service_locator.J.inxYp'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repository' => function (): \App\Repository\BaguetteRepository {
    return ($this->privates['App\Repository\BaguetteRepository'] ?? $this->load('getBaguetteRepositoryService.php'));
}));
