<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qv2nQlj' shared service.

return $this->privates['.service_locator.qv2nQlj'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repository' => function (): \App\Repository\MaisonRepository {
    return ($this->privates['App\Repository\MaisonRepository'] ?? $this->load('getMaisonRepositoryService.php'));
}));
